### ISSUE TITLE
Performance stats in readme?

### ISSUE THREAD

**Issue by paul-hammant** [qaware/go-offline-maven-plugin#1]
Life with and without go-offline-maven-plugin would mean that a project would change a developer experience how?  If faster builds (after first use), then what does that look like in terms of mins/secs or a percentage improvement?  There's developer experience on workstation, but there's also the same timing imorvements in CI of course, and if the % is different then maybe it could be called out.

**Comment by Theoderich** [comment]
Good Idea. I will look into making measurements comparing the go-offline-maven-plugin, maven-dependency-plugin and no prefetching.

**Comment by paul-hammant** [comment]
This is how we sell things :) DHH would speak about RubyOnRail's 10x productivity boost over enterprise Java back in 2004/5/6.

**Comment by Theoderich** [comment]
Performance-wise the go-offline plugin does not really outperform the default maven build. But that is not the point of the plugin. Closing this issue
