### ISSUE TITLE
resolve-dependencies does not download all dependencies in 1.2.1

### ISSUE THREAD

**Issue by uce** [qaware/go-offline-maven-plugin#14]
The following dependency graph fails with version `1.2.1` of `go-offline-maven-plugin`, but works with `1.1.0`.

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] repro-go-offline-maven-plugin
[INFO] repro-child-module
[INFO] repro-main-module
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building repro-go-offline-maven-plugin 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ repro-go-offline-maven-plugin ---
[INFO] com.github.uce:repro-go-offline-maven-plugin:pom:1.0-SNAPSHOT
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building repro-child-module 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ repro-child-module ---
[INFO] com.github.uce:repro-child-module:jar:1.0-SNAPSHOT
[INFO] \- org.xerial:sqlite-jdbc:jar:3.20.1:compile
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building repro-main-module 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ repro-main-module ---
[INFO] com.github.uce:repro-main-module:jar:1.0-SNAPSHOT
[INFO] \- com.github.uce:repro-child-module:jar:1.0-SNAPSHOT:compile
[INFO]    \- org.xerial:sqlite-jdbc:jar:3.25.2:compile
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] repro-go-offline-maven-plugin ...................... SUCCESS [  0.440 s]
[INFO] repro-child-module ................................. SUCCESS [  0.041 s]
[INFO] repro-main-module .................................. SUCCESS [  0.053 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.893 s
[INFO] Finished at: 2019-10-20T16:28:24+02:00
[INFO] Final Memory: 18M/309M
[INFO] ------------------------------------------------------------------------
```

Note the two different versions `org.xerial:sqlite-jdbc:jar:3.20.1:compile` and `org.xerial:sqlite-jdbc:jar:3.25.2:compile`. In `1.1.0`, both dependencies are downloaded whereas in `1.2.1` only the first one is downloaded.

---

I've attached a sample Maven project in [repro-go-offline-maven-plugin.zip](https://github.com/qaware/go-offline-maven-plugin/files/3747951/repro-go-offline-maven-plugin.zip) that reproduces the issue in Docker. There are two Dockerfiles that only differ in the used `go-offline-maven-plugin` version.

```bash
# Fails with [ERROR] Failed to execute goal on project repro-main-module: Could not resolve dependencies for project com.github.uce:repro-main-module:jar:1.0-SNAPSHOT: Cannot access central (https://repo.maven.apache.org/maven2) in offline mode and the artifact org.xerial:sqlite-jdbc:jar:3.25.2 has not been downloaded from it before. -> [Help 1]
docker build -f Dockerfile-go-offline-maven-plugin-1.2.1 .
```

```bash
# Succeeds
docker build -f Dockerfile-go-offline-maven-plugin-1.1.0 .
```

There is some trickiness in reproducing this issue. The root pom imports a BoM that sets a property which `repro-child-module` overwrites. `repro-main-module` depends on `repro-child-module` and the `resolve-dependencies` goal only downloads the version specified in `repro-child-module` instead of the overwritten one from the BOM.

---

Let me know if you need more input or there is an issue in the example/I'm doing something unexpected here.

**Comment by Theoderich** [comment]
Thank you for the great reproducer! I will look into it as soon as I can

**Comment by Theoderich** [comment]
@uce 
Hi, sorry I was out sick the last week and could not look at the problem.
I think I found the problem. Are you able to build the current master and confirm that it works for you now?

**Comment by uce** [comment]
@Theoderich Thanks for looking into it. I will do it by end of this week and report back.

**Comment by uce** [comment]
@Theoderich I can confirm that the current `master` as of c38c2c79ffdf645ef3d9d02fb84e21e361ff2aa9 fixes the issue. 👍 Thanks for fixing this.

<details><summary>More details</summary>
<p>

For reference, I adopted the `Dockerfile` in the repro as follows:

```Dockerfile
FROM maven:3.5.3-jdk-8

COPY pom.xml .
COPY repro-main-module/pom.xml repro-main-module/pom.xml
COPY repro-child-module/pom.xml repro-child-module/pom.xml
COPY go-offline-maven-plugin go-offline-maven-plugin/

RUN cd go-offline-maven-plugin \
  && mvn clean install \
  && cd .. \
  && mvn -f pom.xml de.qaware.maven:go-offline-maven-plugin:1.3.0-SNAPSHOT:resolve-dependencies \
  && mvn -f repro-main-module/pom.xml de.qaware.maven:go-offline-maven-plugin:1.3.0-SNAPSHOT:resolve-dependencies \
  && mvn -f repro-child-module/pom.xml de.qaware.maven:go-offline-maven-plugin:1.3.0-SNAPSHOT:resolve-dependencies

RUN mvn --offline clean install
```

Then I ran the following commands in the root of the repro:
```bash
git clone git@github.com:qaware/go-offline-maven-plugin.git
docker build -f Dockerfile-go-offline-maven-plugin-1.3.0-SNAPSHOT .
```

The build succeeds and I see all expected dependency versions being downloaded.
</p>
</details>

**Comment by Theoderich** [comment]
I have built a Release 1.2.3 that should appear on maven-central in a few days. Note that my fix initially introduced a new bug that is now fixed on master. So please upgrade to 1.2.3 as soon as it is available

**Comment by Theoderich** [comment]
After some hickups, 1.2.3 is finally released :)
