### ISSUE TITLE
Support classifier in DynamicDependency

### ISSUE THREAD

**Issue by tobia** [qaware/go-offline-maven-plugin#15]
I'm trying to pre-download a dependency that has a classifier in the file name:

http://repo.maven.apache.org/maven2/com/querydsl/querydsl-apt/4.2.1/querydsl-apt-4.2.1-jpa.jar

I tried adding `<classifier>` but it doesn't seem to be supported:

    <DynamicDependency>
        <groupId>com.querydsl</groupId>
        <artifactId>querydsl-apt</artifactId>
        <version>4.2.1</version>
        <classifier>jpa</classifier>
        <repositoryType>MAIN</repositoryType>
    </DynamicDependency>

**Comment by Theoderich** [comment]
classifier is indeed not supported, but should be easy to add. I am looking into it.

**Comment by Theoderich** [comment]
Implemented and released version 1.2.2 . Should appear in the maven-central-repository in the next few days. If you do not want to wait, you can checkout the 1.2.2 tag and build it yourself
