### ISSUE TITLE
With multi-module build runs for one stage and skips the rest

### ISSUE THREAD

**Issue by dbrennan** [qaware/go-offline-maven-plugin#18]
I'm no maven expert, but I followed the instructions in the readme and when running `mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies` .  The first one finishes with SUCCESS and all the rest are SKIPPED.  Not sure why or how to further debug after digging for a while.

**Comment by Theoderich** [comment]
Hi, sorry for the slow answer.
This is completely normal since the plugin is a so called "reactor" plugin which means it runs only once for your whole reactor build. The plugin will download all dependencies for all listed modules, even if they are listed as SKIPPED"
