### ISSUE TITLE
Support downloading javadoc

### ISSUE THREAD

**Issue by garethahealy** [qaware/go-offline-maven-plugin#4]
Currently supports download sources, but would also be nice if javadoc could be downloaded.

Main reason, can just use this plugin instead of this plugin + dependancy:resolve

**Comment by Theoderich** [comment]
Implemented and pushed as Version 1.1.0
Please let me know if it works as expected for you

**Comment by garethahealy** [comment]
Thanks for the quick turnaround. 

lgtm.

**Comment by Theoderich** [comment]
Fixed in 1.1.0
