### ISSUE TITLE
Plugin hangs

### ISSUE THREAD

**Issue by lassewesth** [qaware/go-offline-maven-plugin#5]
Hey,

I had a play. Your plugin hangs after a few hundred downloads. I can kill it and start again, and it completes.

To reproduce:

1) `git clone git@github.com:neo4j/neo4j.git`
2) `mvn de.qaware.maven:go-offline-maven-plugin:1.1.0:resolve-dependencies -DexcludeGroupIds=org.neo4j -Dmaven.repo.local=lasse-playing --batch-mode`

Good effort otherwise! I have a working workaround for https://issues.apache.org/jira/browse/MDEP-568 (which involves compiling) but yours is much more elegant.

**Comment by Theoderich** [comment]
I just tested it and i cannot reproduce the problem on my machine.
Can you provide me with your "mvn -version" output?

**Comment by lassewesth** [comment]
```
$ mvn --version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: /opt/maven/latest
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.1", arch: "x86_64", family: "mac"
```

**Comment by Theoderich** [comment]
I think you are running into [MNG-6323](https://issues.apache.org/jira/browse/MNG-6323). Can you please try to upgrade to maven 3.5.3 or 3.5.4 and check if the problem persists?

**Comment by lassewesth** [comment]
@Theoderich thanks got it working after updating Maven and Java:

```
$ mvn --show-version --batch-mode de.qaware.maven:go-offline-maven-plugin:1.1.0:resolve-dependencies -DexcludeGroupIds=org.neo4j -Dmaven.repo.local=lasse-playing7
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: /opt/maven/latest
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.1", arch: "x86_64", family: "mac"
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/fr/jcgay/maven/maven-profiler/2.4/maven-profiler-2.4.pom
...
```
